### ISSUE TITLE
Bring adapter tests up to date

### ISSUE THREAD

**Issue by jkeczan** [gadelkareem/sails-dynamodb#12]
The adapter integration tests fails on Sails v0.11. I get the following error when running `npm test`:

```
> sails-dynamodb@0.12.1 test /Users/jeremykeczan/Projects/web/moneta/node_modules/sails-dynamodb
> node test/integration/runner -R spec -b

/Users/jeremykeczan/Projects/web/moneta/node_modules/sails-dynamodb/test/integration/runner.js:22
    throw new Error(
          ^
Error: 
Could not read supported interfaces from "sails-adapter"."interfaces"
in this adapter's `package.json` file ::
{ [Error: Cannot find module 'root-require'] code: 'MODULE_NOT_FOUND' }
    at Object.<anonymous> (/Users/jeremykeczan/Projects/web/moneta/node_modules/sails-dynamodb/test/integration/runner.js:22:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

I have install require-root both globally and locally with no success. Any suggestions on how to get this to work with Sails v0.11?

**Comment by devinivy** [comment]
The tests are buggered!  I just opened #13.  The branch on that PR will run the tests– you'll see that it's poorly configured, though, and the tests will fail.  I'd like to see more work done on this.
